### PR TITLE
feat: add `handle_withdraw_msg`

### PR DESCRIPTION
**Pull request by silathdiir**
Already update `testdata`.

### CODE REVIEW

**Comment by HAOYUatHZ** [comment]
LGTM

**Comment by lispc** [comment]
using 0 as old balance is ok now.

We should also add a withdraw line in data.txt ?

**Comment by silathdiir** [comment]
> using 0 as old balance is ok now.
> 
> We should also add several withdraw lines in data.txt ?

Will generate `data.txt` with PR https://github.com/fluidex/dingir-exchange/pull/312

**Comment by silathdiir** [comment]
@lispc @HAOYUatHZ Please help review the code again. I update `testdata` from `exchange` with `WithdrawMessage`.

**Review by HAOYUatHZ — APPROVED** [review]

**Pull request merged**
